openapi: 3.0.0
info:
  title: IFTTT Applet Health Checker
  description: A plugin that allows the user to check her applet health statuses.
  version: 1.0.0
paths:
  /check_health:
    get:
      summary: Check Applets Health
      description: Checks the health status of IFTTT installed applets
      operationId: checkHealth
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                 $ref: '#/components/schemas/checkHealthResponse'
components:
  schemas:
    checkHealthResponse:
      type: object
      properties:
        statuses:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
                description: The name of the applet.
              slug:
                type: string
                description: The slug of the applet.
              status:
                type: string
                description: The status of the applet.
